#!/usr/bin/env bash
# Parse a Windows msinfo32 export into docs/devices/<id>.md (draft).
#
# Usage:
#   ./scripts/import-msinfo.sh /path/to/tablet.txt tablet-02
#   ./scripts/import-msinfo.sh /path/to/tablet.txt rca-other --force
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SRC="${1:-}"
ID="${2:-}"
FORCE="${3:-}"

if [[ -z "$SRC" || -z "$ID" ]]; then
  echo "Usage: $0 <msinfo-export.txt> <device-id> [--force]" >&2
  exit 1
fi
[[ -f "$SRC" ]] || { echo "ERROR: not a file: $SRC" >&2; exit 1; }

OUT="$ROOT/docs/devices/${ID}.md"
if [[ -f "$OUT" && "$FORCE" != "--force" ]]; then
  # Always write a .from-msinfo.md sidecar if target exists
  OUT="$ROOT/docs/devices/${ID}.from-msinfo.md"
  echo "NOTE: $ROOT/docs/devices/${ID}.md exists — writing $OUT (merge by hand or --force)"
fi

python3 - "$SRC" "$OUT" "$ID" <<'PY'
import sys
from pathlib import Path
from collections import defaultdict

src, out, unit_id = Path(sys.argv[1]), Path(sys.argv[2]), sys.argv[3]
raw = src.read_bytes()
if raw[:2] == b"\xff\xfe":
    text = raw.decode("utf-16-le")
elif raw[:2] == b"\xfe\xff":
    text = raw.decode("utf-16-be")
else:
    text = raw.decode("utf-8", errors="replace")

sections = defaultdict(list)
cur = "ROOT"
for line in text.splitlines():
    line = line.strip("\r")
    if line.startswith("[") and line.endswith("]"):
        cur = line[1:-1]
        continue
    if not line or line.startswith("Item"):
        continue
    if "\t" in line:
        a, b = line.split("\t", 1)
        sections[cur].append((a.strip(), b.strip()))

def get(sec, key, default=""):
    for k, v in sections.get(sec, []):
        if k == key:
            return v
    return default

ss = "System Summary"
mfr = get(ss, "System Manufacturer")
model = get(ss, "System Model")
stype = get(ss, "System Type")
cpu = get(ss, "Processor")
ram = get(ss, "Installed Physical Memory (RAM)")
bios = get(ss, "BIOS Version/Date")
bmode = get(ss, "BIOS Mode")
sb = get(ss, "Secure Boot State")
board = get(ss, "BaseBoard Product")
role = get(ss, "Platform Role")
sname = get(ss, "System Name")
osn = get(ss, "OS Name")
osv = get(ss, "Version")

disp_name = get("Display", "Name")
disp_res = get("Display", "Resolution")
disp_ram = get("Display", "Adapter RAM")

# disks: prefer fixed
disks = []
cur_model = None
for k, v in sections.get("Disks", []):
    if k == "Model":
        cur_model = v
    if k == "Size" and cur_model and "USB" not in cur_model and "Removable" not in str(v):
        disks.append((cur_model, v))
        cur_model = None
    if k == "Media Type" and v == "Fixed hard disk" and cur_model:
        pass

disk_s = "; ".join(f"{m} ({s})" for m, s in disks[:3]) or "see raw export"

# touch heuristic
touch = []
for sec, pairs in sections.items():
    for k, v in pairs:
        blob = f"{k} {v}".lower()
        if "goodix" in blob or "digitizer" in blob or ("touch" in blob and "keyboard" not in blob):
            if v and v not in touch and len(v) < 120:
                touch.append(v)
touch_s = "; ".join(touch[:5]) or "see Device Manager / re-check after Linux install"

body = f"""# Device: {mfr} {model}

**Unit ID:** `{unit_id}`  
**Source:** Windows msinfo export `{src.name}` (auto-import)  
**Hostname (Windows):** {sname}  
**Tracking:** [sls-camera#7](https://github.com/tmdrake/sls-camera/issues/7)  
**Field kit:** Kinect 360 + portable power — [kinect-portable-power.md](kinect-portable-power.md)

## Summary

| Field | Value | SLS notes |
|-------|--------|-----------|
| Manufacturer | {mfr} | |
| Model | {model} | |
| Board | {board} | |
| CPU | {cpu} | 64-bit Lubuntu if CPU is x86_64-capable |
| RAM | {ram} | |
| System type (Windows) | {stype} | X86 = often 32-bit Win; still prefer **amd64** Linux if CPU allows |
| Platform role | {role} | |
| OS (when captured) | {osn} {osv} | |
| BIOS | {bios} | |
| BIOS mode | {bmode} | |
| Secure Boot | {sb} | |
| Display | {disp_name} ({disp_ram}) | |
| Resolution (Windows) | {disp_res} | Portrait if height > width |
| Storage (fixed) | {disk_s} | |
| Touch (heuristic) | {touch_s} | |

## Field kit pairing

| Kit | Notes |
|-----|--------|
| Kinect 360 + portable PSU | See [kinect-portable-power.md](kinect-portable-power.md) |
| Media stick | SLS-MEDIA |

## Appliance status

| Check | Result | Date |
|-------|--------|------|
| Lubuntu 26.04 install | pending | |
| install-from-usb | pending | |
| Touch | pending | |
| Kinect + portable PSU | pending | |
| Settings usable | pending | |
| Captures | pending | |
| Quit power-off | pending | |

## Notes

_Auto-generated by `scripts/import-msinfo.sh`. Edit freely; re-import with `--force` overwrites this file if named as the unit id._
"""
out.write_text(body)
print(f"Wrote {out}")
PY

echo "Review and merge into docs/devices/ as needed."
echo "Update docs/devices/README.md fleet table for unit: $ID"
